lalten/rules_appimage

appimage/appimage.bzl, appimage/private/runfiles.bzl, appimage/private/tool/tool.py, tests/test_appimage.py
Symlinks are incorrectly calculated. This patch should make all symlinks valid.
Before:
```
❯ tree squashfs-root
squashfs-root
├── AppRun
├── AppRun.desktop
├── AppRun.png
└── tests
├── test_py -> AppDir/tests/test_py.runfiles/rules_appimage/tests/test_py
└── test_py.runfiles
├── bazel_tools
│   └── tools
│       └── python
│           └── py3wrapper.sh
├── __init__.py
├── py_deps
│   ├── __init__.py
│   └── pypi__click
│       ├── click
│       │   ├── _compat.py
│       │   ├── core.py
│       │   ├── decorators.py
│       │   ├── exceptions.py
│       │   ├── formatting.py
│       │   ├── globals.py
│       │   ├── __init__.py
│       │   ├── parser.py
│       │   ├── py.typed
│       │   ├── shell_completion.py
│       │   ├── _termui_impl.py
│       │   ├── termui.py
│       │   ├── …
```
=> Fix broken symlink targets

deps.bzl
This fixes:
```
Traceback (most recent call last):
File "/home/laurenz/.cache/bazel/_bazel_laurenz/a5a1ba7b6df8b0a1a9c5bbd01b7812f3/external/bazel_skylib/rules/native_binary.bzl", line 42, column 22, in _impl
return _impl_rule(ctx, ctx.attr.is_windows)
File "/home/laurenz/.cache/bazel/_bazel_laurenz/a5a1ba7b6df8b0a1a9c5bbd01b7812f3/external/bazel_skylib/rules/native_binary.bzl", line 33, column 23, in _impl_rule
files = depset(items = [out]),
Error in depset: depset() got unexpected keyword argument 'items'
ERROR: /home/laurenz/Documents/Github/rules_appimage/appimage/private/tool/BUILD:5:14: Analysis of target '//appimage/private/tool:appimagetool' failed
```
=> Update Skylib to 1.1.1

deps.bzl
This is nice when you want to use your own mirror of the appimage deps -- e.g. because you don't want to load from the internet during the build.
=> Use existing appimagetool/AppImageKit deps when available

appimage/private/tool/tool.py
Make appimagetool output print to stderr instead of stdout when it is printed
=> Send appimagetool output to stderr

appimage/private/runfiles.bzl
Previously, if ctx.attr.binary.label.package was empty (this can happen in toplevel targets, or external dependencies), the _binary_name function would return a path with a leading /, which messes up path lookups.
With this patch, the leading slash is prevented if the target package is the emtpy string.
=> Prevent accidentally-absolute paths for external binaries

appimage/private/runfiles.bzl, appimage/private/tool/tool.py, tests/BUILD, tests/test.py
For a test I'm using `@rules_python//tools:wheelmaker`, which is external to this repo. Without the fix, the test would complain something like this:
```
AssertionError: /tmp/appimage_extracted_b8e1ae75ecd774d7f70b9c24383e1c8b/AppRun: line 5: /tmp/appimage_extracted_b8e1ae75ecd774d7f70b9c24383e1c8b/tools/wheelmaker.runfiles/rules_appimage/tools/wheelmaker: No such file or directory
```
because the workdir is not correct.
=> Allow binary targets in external Bazel repos

appimage/private/runfiles.bzl, tests/BUILD, tests/test.py, tests/testrules.bzl
* Remove the unused `_layer_*_path` functions lifted from rules_docker
* Fix the runfiles symlinks target path to be under runfiles where it belongs
* Add a test
=> Fix runfiles symlinks

deps.bzl
The https://github.com/bazelbuild/bazel-skylib/releases/tag/1.3.0 release of Skylib has an incompatible change where a symlink is used for native_binary rules. This can only work if the src is executable so we need to set that as well on the http_file.
=> Upgrade to Skylib 1.3.0

BazelizedMksquashfs.md, appimage/appimage.bzl, appimage/private/tool/BUILD, appimage/private/tool/tests/test_tool.py, appimage/private/tool/tool.py, deps.bzl, tests/BUILD
Until now, rules_appimage used `appimagetool` from https://github.com/AppImage/AppImageKit to create the actual .AppImage artifact from the prepared AppDir. This works but does not provide much value add over creating the squashfs ourselves and concating it to an appimage runtime (which is essentially what appimagetool does).
This PR replaces appimagetool with this process. The big advantages are:
* Can provide a custom mksquashfs to use
* Can completely customize all mksquashfs options
* Easier to replace the AppImage runtime, e.g. with the upcoming static one that includes libfuse3 in it.
=> Replace appimagetool with direct mksquashfs invocation and runtime concatenation

appimage/appimage.bzl
RunEnvironmentInfo is only available in Bazel >= 5.3
testing.TestEnvironment is deprecated in latest Bazel, but at least it works even on Bazel 4 :) https://bazel.build/rules/lib/testing#TestEnvironment
Closes https://github.com/lalten/rules_appimage/issues/29
=> Replace RunEnvironmentInfo with TestEnvironment

.github/workflows/ci.yaml, README.md, appimage/appimage.bzl, appimage/private/tool/BUILD, appimage/private/tool/tests/BUILD, tests/BUILD
Turn on all the warnings that are disabled by default. See https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md#linter
=> Use `-warnings all` with buildifier

appimage/private/tool/mkappimage.py, tests/BUILD, tests/runfiles_test.sh
Thanks @fughilli for finding this issue
Fixes https://github.com/lalten/rules_appimage/issues/56
=> Explicitly set RUNFILES_DIR

.github/workflows/ci.yaml, appimage/appimage.bzl, appimage/private/tool/cli.py, appimage/private/tool/mkappimage.py, tests/BUILD, tests/appimage_test_cc_with_sh_test.sh, tests/test.cc, tests/test.py, tests/tool/tests/test_cli.py, tests/tool/tests/test_mkappimage.py
This PR improves environment handling:
* The `env` of the `binary` target is kept if the target rule supports it
* That `env` dict is updated with the `env` attr of the appimage target
* The resulting environment is set up in the Appimage entrypoint. This means the `env` attrs have an effect even if not running through Bazel, but in a standalone Appimage.
Fixes https://github.com/lalten/rules_appimage/issues/53
=> Propagate env attr

appimage/appimage.bzl, appimage/private/runfiles.bzl, tests/BUILD, tests/appimage_data_file.txt, tests/appimage_data_filegroup.txt, tests/test.py
This allows adding custom data to an appimage. The use case is a setup in which one would normally use a `label_flag` option to add additional runfiles to a given executable. We want to encode some useful values of that `label_flag` in the appimage.
=> Add a data attribute to add additional runfiles to the appimage

appimage/private/tool/BUILD, appimage/private/tool/mkappimage.py, deps.bzl, tests/test_appimage.py, third_party/squashfs-tools.BUILD, third_party/zstd.BUILD
Having Bazel build `mksquashfs` from source should help with cross-target appimage building, which has mksquashfs running in exec configuration. With this setup, Bazel should do the right (:tm:) thing automatically. There is no need to pull in multiple mksquashfs static binaries.
Note that the mksquashfs we build here only supports gzip and zstd compressors. This is the same set as in the previous mksquashfs from https://github.com/lalten/static-tools/releases/tag/build-2022-10-02-f8b7a56
The zlib (for gzip) is taken directly from Bazel itself, so only zstd is a new external transitive source dependency.
=> Switch to Bazel-built mksquashfs

appimage/private/tool/BUILD, appimage/private/tool/mkappimage.py, requirements.in, requirements.txt
**What changed?**
The runfiles lib is being accessed as a pip dependency rather than as part of the rules_python.
**Why is this good?**
This change will hopefully allow rules_appimage to be usable from a WORKSPACE.bzlmod of a project with bzlmod enabled. I am not 100% sure about this theory, but there is no harm in this change IMO. As soon as this change is merged, I will try the new version and verify that rules_appimage works in a project when listed in a WORKSPACE.bzlmod
=> use bazel-runfiles instead of accessing runfiles from rules_python

README.md
Let's use what's in the release notes
=> Remove verbatim WORKSPACE instrcuctions from README.md

tests/test.cc, third_party/squashfs-tools.BUILD
If the main repo's .bazelrc adds compiler flags to enable (more) warnings, this will hide them.
=> Silence compiler issues

third_party/squashfs-tools.BUILD
```
INFO: From Compiling mksquashfs.c [for tool]:
external/squashfs-tools/mksquashfs.c:4919:6: warning: variable 'i' set but not used [-Wunused-but-set-variable]
int i, res, first = TRUE, same = FALSE;
^
1 warning generated.
```
=> Mute `-Wunused-but-set-variable`

.github/workflows/ci.yaml
Testing with various Python versions was useful when rules_appimage used whatever Python interpreter was in the host repo. But since https://github.com/lalten/rules_appimage/pull/86 we actually require pip deps brought that come from rules_appimage's own pypi-bazel-repo. We may as well use the hermetic Python interpreter that comes with that.
This means we don't need to test against all Python versions anymore, because mkappimage will always run with the Python configured in https://github.com/lalten/rules_appimage/blob/71e9728f92e2f6713ffbff3b8d78135d6e4ca6f1/WORKSPACE#L13
=> Remove Python test matrix

.github/workflows/ci.yaml, MODULE.bazel, extensions.bzl
There's an open PR to add Bzlmod support (https://github.com/lalten/rules_appimage/pull/78), but it hasn't landed and it's out of date.
This PR adds Bzlmod support for 1.3.0. I've tested it locally within the project and by pulling this in as a dependency from another workspace.
=> Add Bzlmod support

.bazelrc, appimage/private/tool/mkappimage.py, tests/BUILD, tests/dir/subdir/invalid_link, tests/test.py, tests/test_appimage.py, tests/testrules.bzl
Support dangling symlinks created with `ctx.actions.declare_symlink` and remove invalid_link tests that are not compativle with remote caching
=> Support dangling symlinks created with `ctx.actions.declare_symlink`

tests/BUILD, tests/test.py, tests/test_appimage.py
Not all remote cache implementations actually support this. See https://cs.opensource.google/bazel/bazel/+/release-7.0.1:src/main/java/com/google/devtools/build/lib/remote/UploadManifest.java;l=212
=> Remove absolute symlink tests

BUILD, MODULE.bazel
This will allow a root module using a python version other than 3.11 to use the rules_appimage
=> support root modules using python 3.8

deps.bzl
rules_python have dropped support for Bazel 5: https://github.com/bazelbuild/rules_python/pull/1613
This PR will downgrade rules_python to make the Bazel 5 CI matrix job green.
I'll make a new release after this lands, which will be the last Bazel 5 compatible version of rules_appimage.
=> Downgrade WORKSPACE rules_python to make Bazel 5 CI green

.bcr/patches/old-gcc-std20.patch, MODULE.bazel
* Add the patch file that was manually added for the first BCR release
* Remove MODULE.bazel stamping to have the publish-to-bcr bot autogenerate a patch with the right version. See https://github.com/bazel-contrib/publish-to-bcr/blob/e765a5054ffa69f7c6950b568d2020fd1bfaf653/src/domain/create-entry.ts#L222-L225
=> Prepare release

MODULE.bazel
I'm suspecting https://github.com/bazel-contrib/publish-to-bcr/issues/95 is why publish-to-bcr-bot doesn't do its thing
=> Add back in module version

.bcr/presubmit.yml
Comply with future enforcement of https://github.com/bazelbuild/bazel-central-registry/pull/1387
=> Add bazel test matrix for BCR presubmit tests

MODULE.bazel, deps.bzl
With https://github.com/bazelbuild/bazel-central-registry/pull/1406 landed, depend on BCR mksquashfs
=> Use BCR squashfs when using Bzmlod

appimage/private/runfiles.bzl, appimage/private/tool/mkappimage.py, tests/BUILD, tests/test.py, tests/test_appimage.py
This PR changes how symlink runfiles are handled in appimages.
The effect of this can be seen by mounting an AppImage and running `tree` on the mounted dir:
```
❯ bazel run //tests:appimage_py -- --appimage-mount
/tmp/.mount_appimaHmeNGb
❯ tree /tmp/.mount_appimaHmeNGb
```
| Current `main` | `main` with BUILD changes from this PR (added `dot_symlink` and `dotdot_symlink`) | This PR |
|--------|--------|--------|
| ![image](https://github.com/lalten/rules_appimage/assets/11611719/05fa305f-ba9f-4458-9ec6-c188de331c48) | ![image](https://github.com/lalten/rules_appimage/assets/11611719/cadecec4-aeff-49a0-80de-7989380dbac0) | ![image](https://github.com/lalten/rules_appimage/assets/11611719/c5b2729c-575a-458a-b811-00af668bad81) | 
Before:
* Symlinks are followed, and (if found) the link …
=> Change symlink following behavior

.bazelrc, tests/BUILD
The .bazelrc was not read in BCR with the `bcr_test_module` root key in the presubmit.yaml removed.
=> Move the `-std=c++20` option to the BUILD target

.bcr/presubmit.yml
It was causing behavior changes breaking the build in BCR CI. See https://github.com/bazelbuild/bazel-central-registry/pull/1488#issuecomment-1986860002
=> Reinstate `bcr_test_module` root key in presubmit.yml

appimage/appimage.bzl, appimage/private/tool/mkappimage.py, tests/build_working_directory/BUILD, tests/build_working_directory/entrypoint.sh, tests/build_working_directory/test.sh
This PR reworks the AppRun entrypoint generation a bit. Major changes are:
* Don't re-export some build context environment vars to the AppRun script
* Fall back to using `$PWD` (which is now correct and not the build time PWD anymore) for `BUILD_WORKING_DIRECTORY` if neither `$BUILD_WORKING_DIRECTORY` nor `$OWD` is available due to https://github.com/AppImage/type2-runtime/issues/23
Closes https://github.com/lalten/rules_appimage/issues/156
=> Set `BUILD_WORKING_DIRECTORY` even when `APPIMAGE_EXTRACT_AND_RUN=1`

MODULE.bazel, appimage/appimage.bzl, appimage/private/tool/cli.py, appimage/private/tool/mkappimage.py, deps.bzl, tests/tool/tests/test_cli.py, tests/tool/tests/test_mkappimage.py
The [AppImage Type2 Spec][appimage-spec] specifies that the contained [AppDir][appdir-spec] may contain a  [.desktop file][desktop-spec]. To my knowledge this is only used with [appimaged][appimaged] and entirely optional.
The only reason for very basic icon file support to exist in rules_appimage is that the first implementation used [appimagetool][appimagetool] to build appimages, which makes using an icon file mandatory.
I don't know of anyone who actually used this feature. Dropping this feature is long overdue and should slightly speed up builds as well as produce smaller appimage artifacts because we don't need to copy, compress, and store the png file.
[appdir-spec]: https://rox.sourceforge.net/desktop/AppDirs.html
[appimage-spec]: …
=> Remove icon support

.pre-commit-config.yaml, appimage/private/mkappdir.py, examples/hello.py, pyproject.toml, tests/BUILD, tests/mkappdir_test.py
Added some more unit tests and noticed that `copy_file_or_dir` wasn't doing exactly what I expected it to do for dangling symlinks.
=> Correct `copy_file_or_dir` behavior for dangling symlinks

appimage/appimage.bzl, appimage/private/mkappdir.py, tests/mkappdir_test.py
This changes the way that appimage squashfs files are built with rules_appimage. Instead of taring up all the files and then providing that to mksquashfs we build a pseudo file definitions list that tells mksquashfs where to get all the files from. This avoids the expensive tar operation when inputs change (building the pseudofile defs is pretty cheap).
The mksquashfs action does take longer now (likely because it has to do thousands of `sh -c "cat {file}"` invocations) but overall the build times are lower for large appimages and the cachability remote execution ability should be better.
There was also an issue with the most recent MkAppDir implementation where the tar was populated in a ThreadPool which was not deterministic, so file order inside the .tar and .sqfs may change, leading …
=> Use mksquashfs pseudofile definitions for AppImage build

appimage/appimage.bzl, appimage/private/BUILD, appimage/private/mkappimage.sh
Merge steps into a single `AppImage` mnemonic. This makes builds faster, particularly on systems with slow I/O (thinking EBS volumes here) as Bazel doesn't need to shuffle all the inputs around for every action. It also simplifies what needs to be remote-cached and/or executed, so I dropped the `execution_requirements` tags again for now.
=> Merge steps into a single `AppImage` mnemonic

.github/workflows/ci.yaml, MODULE.bazel, appimage/appimage.bzl, tests/analysis_tests/program.sh, tests/determinism/reproducible_shas.sh
Need to add `-all-time 0` to the mksquashfs args to prevent non-deterministic timestamps of files generated from the pseudo file definitions list.
See https://github.com/plougher/squashfs-tools/issues/288
Also add an integration test that checks if rebuilds have stable hashes.
For some there were two minor issues regarding `bazel mod tidy` and a missing `program.sh`, fixed those as well.
=> Fix build determinism

appimage/private/mkappdir.py, tests/mkappdir_test.py
Hard-link pseudo files instead of `cat`ing them to enable duplicate detection.
Also use 0 as mode of symlinks as it's ignored anyways.
See https://github.com/plougher/squashfs-tools/issues/289
One unfortunate side effect is that the $label.pseudofile_defs.txt output contains absolute paths. The reason is that `l` hard-link mode doesn't follow symlinks, the input must be `.resolve()`d.
=> Hard-link pseudo files

MODULE.bazel
Upgrade `with_cfg.bzl` to https://github.com/fmeum/with_cfg.bzl/releases/tag/v0.6.0 to fix `Error: 'struct' value has no field or method 'AppleDebugOutputs'` in https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/72#019367bc-a37c-4ae9-acf2-4a0ccdfdf8c9 and work towards https://github.com/bazelbuild/bazel-central-registry/issues/3260
=> Upgrade with_cfg.bzl

appimage/private/mkapprun.bzl
Don't call `/usr/bin/dirname` in AppRun to improve hermeticity and reduce runtime dependency
```console
❯ type dirname
dirname is /usr/bin/dirname
```
=> Don't call `/usr/bin/dirname` in AppRun

appimage/private/mkappdir.py, tests/mkappdir_test.py
Using `h` pseudo file definition from https://github.com/plougher/squashfs-tools/commit/58fab67d4a1b974b938ebc37c369449216a4ff2b removes absolute paths (which were necessary because of https://github.com/plougher/squashfs-tools/commit/58fab67d4a1b974b938ebc37c369449216a4ff2b) from the optional `.pseudofile_defs.txt` output.
Compare `bazel-bin/tests/appimage_test_sh.pseudofile_defs.txt` when running ` bazel build //tests:appimage_test_sh --output_groups appimage_debug --platforms //:linux_x86_64`
Before:
```
AppRun l /private/var/tmp/_bazel_laltenmueller/62b467eb38cd779b06b4f1f1a7ca9ad5/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/tests/appimage_test_sh.AppRun
"tests" d 755 0 0
"tests/test_sh" s 0 0 0 test_sh.runfiles/_main/tests/test_sh
"tests/test_sh.repo_mapping" l …
```
=> Use sqfs 4.7 relative hard link mode `h`
